New events: add and remove delegates
Kwenta/kwenta-subgraph pull request #160
Opened 2023-11-01 21:39 UTC by LeifuChen

Added two events in this PR.
- DelegatedAccountAdded
- DelegatedAccountRemoved

2023-11-03 19:21 UTC, avclarke requested changes

2023-11-03 19:21 UTC, avclarke commented on subgraphs/perps.graphql
> +type DelegatedAccountAdded @entity {
Instead of two separate entities I think we can have a single one and remove the entity on DelegateRemoved with `store.remove('Delegate', id)`

2023-11-06 12:44 UTC, LeifuChen commented on subgraphs/perps.graphql
> +type DelegatedAccountAdded @entity {
Good idea. Pushed the changes. 
I also created a test graph for the delegation management here: https://api.studio.thegraph.com/query/7302/kwenta-account/version/latest

2023-11-06 15:19 UTC, LeifuChen commented on subgraphs/perps.graphql
> +  id: Bytes!
Thanks. Updated.

2023-11-06 15:49 UTC, avclarke approved these changes

2023-11-06 19:15 UTC, merged