[V3] Add traders' pnl to perpsV3Stat
Kwenta/kwenta-subgraph pull request #172
Opened 2024-01-23 12:35 UTC by LeifuChen

2024-01-25 07:24 UTC, avclarke requested changes
Looks good, just a small change required related to the new accounts.

2024-01-25 07:24 UTC, avclarke commented on src/perps-v3.ts
> +    account = new Account(event.params.accountId.toString());
There should never be a case where we get to this event without an account being already created. Instead of creating a partial account here (e.g. there is no owner being set) we should probably just log an error and return.

2024-01-25 07:24 UTC, avclarke commented on src/perps-v3.ts
> +    account = new Account(order.account);
Same for here

2024-01-26 12:26 UTC, LeifuChen commented on src/perps-v3.ts
> +    account = new Account(event.params.accountId.toString());
Good point. Updated.

2024-01-26 12:26 UTC, LeifuChen commented on src/perps-v3.ts
> +    account = new Account(order.account);
Updated. Thanks.

2024-01-29 10:10 UTC, avclarke approved these changes

2024-01-29 10:40 UTC, merged