Add liquidations to trades
Kwenta/kwenta-subgraph pull request #41
Opened 2022-05-11 20:24 UTC by Tburm

Add liquidations as a new trade type. Liquidations are initially created during the `PositionModified` event in order to capture to trade direction (long/short), and is updated during the `PositionLiquidated` event with the trade size and fee.

2022-05-11 21:55 UTC, brossetti1 commented on src/futures.ts
> +    tradeEntity.size = positionEntity.size.gt(ZERO) ? BigInt.fromI32(-1) : BigInt.fromI32(1);
nice solution here

2022-05-11 22:07 UTC, brossetti1 requested changes
just curious - i thought we talked about doing the entire tradeEntity in the `handlePositionLiquidated` event - do we not have enough info on `PositionLiquidatedEvent`?

nice job on this - will approve after response

2022-05-11 22:07 UTC, brossetti1 commented on src/futures.ts
> +    tradeEntity.size = event.params.size.times(tradeEntity.size);
maybe a comment here would help too

```suggestion
    // size will be either -1 or 1 in this scenario (see handlePositionModified for details)
    tradeEntity.size = event.params.size.times(tradeEntity.size);
```

2022-05-11 23:32 UTC, Tburm commented
@brossetti1 That's correct, I was able to put the whole thing into the `PositionLiquidated` event but there is no way to tell which direction the trade goes. `PositionLiquidated` is called after `PositionModified`. `PositionModified` for a liquidation sets all values to zero (margin, size, trade size) so it's impossible to derive direction inside of `PositionLiquidated`.

2022-05-12 13:21 UTC, platschi commented
https://github.com/Kwenta/kwenta/pull/833  has been approved and merged to frontend, so this PR is good to go.

2022-05-12 15:13 UTC, brossetti1 approved these changes

2022-05-13 00:59 UTC, merged